# Generated by Django 5.2.12 on 2026-03-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
